# New fields must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Common
version=2.5.0+26.1
group=com.khazoda.plushables
license=GPLv3

minecraft_version=26.1
minecraft_version_range=[26.1, 26.2)

mod_name=Plushables
mod_author=Khazoda
mod_id=plushables
mod_icon=plushables.png

description=Cute plushies for your home
homepage_url=https://khazoda.com#plushables
sources_url=https://github.com/khazoda-mods/plushables
issues_url=https://github.com/khazoda-mods/plushables/issues

# https://khazoda.com/khazodacore
khazodacore_version=1.0.2+26.1

# https://fabricmc.net/develop
fabric_version=0.145.1+26.1
fabric_loader_version=0.18.4

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)

# Java & Gradle
java_version=25
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
